In [1]:
import netCDF4 as nc
import numpy as np

#fft_path = '/home/jim/Desktop/FFT_notebook/BPMFwFFT/examples/fft_sampling/t4_benzene'
fft_path = '/home/jim/Desktop/FFT_notebook/5.fft_sampling/1AVZ_B:C'
fft_sample_nc = '%s/fft_sample.nc'%fft_path

variable_names = nc.Dataset(fft_sample_nc, 'r').variables
rec_positions = nc.Dataset(fft_sample_nc, 'r').variables["rec_positions"][:]
lig_positions = nc.Dataset(fft_sample_nc, 'r').variables["lig_positions"][:]
lig_com = nc.Dataset(fft_sample_nc, 'r').variables["lig_com"][:]
volume = nc.Dataset(fft_sample_nc, 'r').variables["volume"][:]
nr_grid_points = nc.Dataset(fft_sample_nc, 'r').variables["nr_grid_points"][:]
exponential_sums = nc.Dataset(fft_sample_nc, 'r').variables["exponential_sums"][:]
log_of_divisors = nc.Dataset(fft_sample_nc, 'r').variables["log_of_divisors"][:]

mean_energy = nc.Dataset(fft_sample_nc, 'r').variables["mean_energy"][:]
min_energy = nc.Dataset(fft_sample_nc, 'r').variables["min_energy"][:]
resampled_energies = nc.Dataset(fft_sample_nc, 'r').variables["resampled_energies"][:]
resampled_trans_vectors = nc.Dataset(fft_sample_nc, 'r').variables["resampled_trans_vectors"][:]
print(resampled_trans_vectors[:])
print(resampled_energies[:])

#grid coordinates
origin = nc.Dataset(fft_sample_nc, 'r').variables["origin"][:]
x = nc.Dataset(fft_sample_nc, 'r').variables["x"][:]
y = nc.Dataset(fft_sample_nc, 'r').variables["y"][:]
z = nc.Dataset(fft_sample_nc, 'r').variables["z"][:]
d = nc.Dataset(fft_sample_nc, 'r').variables["d1"][:]

for name in variable_names:
    print(name)

print(lig_positions.shape)
print(resampled_energies.shape)
print(resampled_trans_vectors.shape)
print(np.amin(resampled_energies[0]))
min_index = np.where(resampled_energies[0] == resampled_energies[0].min())
print(min_index)
print(float(resampled_energies[0][min_index]))
print(resampled_trans_vectors[0][min_index])

[[[ 90  81  42]
  [ 90  80  42]
  [ 88  81  41]
  [ 90  79  42]
  [ 89  81  41]
  [ 89  82  41]
  [ 87  80  41]
  [ 90  80  41]
  [ 89  80  41]
  [ 88  80  41]
  [ 90  79  41]
  [135  29  14]
  [ 89  79  41]
  [ 91  78  41]
  [ 88  79  41]
  [ 90  78  41]
  [ 91  80  40]
  [136  30  14]
  [ 89  82  40]
  [137  30  14]
  [ 89  78  41]
  [ 87  79  41]
  [119  34  20]
  [ 90  80  40]
  [ 89  81  40]
  [133  30  12]
  [121  32  18]
  [ 88  82  40]
  [ 88  83  40]
  [135  30  13]
  [120  33  19]
  [ 88  81  40]
  [122  31  17]
  [ 91  79  40]
  [ 88  78  41]
  [119  34  19]
  [119  33  21]
  [ 87  82  40]
  [132  29  12]
  [ 87  83  40]
  [ 89  80  40]
  [120  34  17]
  [134  29  13]
  [122  32  15]
  [121  33  16]
  [121  31  19]
  [122  30  18]
  [121  32  17]
  [136  30  13]
  [136  29  14]
  [119  33  20]
  [ 90  79  40]
  [122  30  17]
  [120  33  18]
  [123  28  19]
  [ 89  77  41]
  [134  30  12]
  [ 86  79  41]
  [122  31  16]
  [ 88  80  40]
  [ 87  78  41]
  [119  32  22]
  [122  

In [2]:
import netCDF4 as nc
import numpy as np

grid_path = '/home/jim/Desktop/FFT_notebook/4.receptor_grid/1AVZ_B:C'
grid_nc = '%s/grid.nc'%grid_path


#parsing some of the netcdf variables from grid.nc
grid_variables = nc.Dataset(grid_nc, 'r').variables
counts = nc.Dataset(grid_nc, 'r').variables["counts"][:]
x = nc.Dataset(grid_nc, 'r').variables["x"][:]
y = nc.Dataset(grid_nc, 'r').variables["y"][:]
z = nc.Dataset(grid_nc, 'r').variables["z"][:]
electrostatic = nc.Dataset(grid_nc, 'r').variables["electrostatic"][:]
lja = nc.Dataset(grid_nc, 'r').variables["LJa"][:]
ljr = nc.Dataset(grid_nc, 'r').variables["LJr"][:]
occupancy = nc.Dataset(grid_nc, 'r').variables["occupancy"][:]
trans_crd = nc.Dataset(grid_nc, 'r').variables["trans_crd"][:]

#DELETE ME: print statements for inspecting the contents of grid.nc
#print(len(occupancy[200][:]))
#print(grid_variables)
kttc = []
for key in grid_variables:
    kttc.append(key)
#    print(grid_variables[key])
print(kttc)
print(counts)
#electrostatic grid is accessed by grid[x][y][z], to be confirmed. Alternative is grid[z][y][x]
#below code accesses electrostatic grid values for 3 points on the same axis
print(electrostatic[0][0][0],electrostatic[0][0][1],electrostatic[0][0][2])
#identifies occupied positions on the grid 
occupied_list = [i for i in range(len(occupancy[50][50])) if occupancy[50][50][i] == 1] 
          
# printing resultant list  
print ("New indices list : " + str(occupied_list)) 

#for i in res_list:
#    print(electrostatic[200][200][i])
    
#print(trans_crd)
#print(trans_crd[:])

def multiply_grids(electrostatic_grid, lja_grid, ljr_grid, occupancy_grid):
    grid_dot = np.empty((electrostatic_grid.shape[0], electrostatic_grid.shape[1], electrostatic_grid.shape[2]))
    for i in range(electrostatic_grid.shape[0]):
        for j in range(electrostatic_grid.shape[1]):
            for k in range(electrostatic_grid.shape[2]):
                grid_dot[i][j][k] = np.dot(electrostatic_grid[i][j][k], lja_grid[i][j][k])
                grid_dot[i][j][k] = np.dot(grid_dot[i][j][k], ljr_grid[i][j][k])
    return grid_dot

def get_meaningful_energies(energies):
    for i in range(energies.shape[0]):
        for j in range(energies.shape[1]):
            for k in range(energies.shape[2]):
                if energies[i][j][k] > 0.5:
                    print(energies[i][j][k])


#result = multiply_grids(electrostatic, lja, ljr, occupancy)
#get_meaningful_energies(result)
#print(result)
for i in trans_crd:
    if i[0] > 140:
        print(i)
    
native_trans = [i for i in range(len(trans_crd[:])) if trans_crd[i][0] == 140] 
print(len(trans_crd))
for point in occupied_list:
    print(trans_crd[point])
# get the center of mass of the crystallographic pose, then, get the center of mass for every
# translation of the native rotation and measure the distance between the two points. Select
# the translation with the nearest center of mass as the "native/crystallographic pose"



[u'lj_sigma_scaling_factor', u'origin', u'd0', u'd1', u'd2', u'spacing', u'counts', u'x', u'y', u'z', u'LJa', u'electrostatic', u'occupancy', u'LJr', u'trans_crd']
[247 247 247]
(4.382767024860179, 4.393615307827583, 4.404389010873258)
New indices list : []
1839


In [3]:
# Create the receptor and ligand grid objects by loading an existing grid calculation result

from grids import RecGrid
from grids import LigGrid

rec_prmtop = "/home/jim/Desktop/FFT_notebook/1.amber/1AVZ_B:C/receptor.prmtop"
lj_sigma_scal_fact = 0.8
rec_inpcrd = "/home/jim/Desktop/FFT_notebook/2.minimize/1AVZ_B:C/receptor.inpcrd"

bsite_file = None
grid_nc_file = "/home/jim/Desktop/FFT_notebook/4.receptor_grid/1AVZ_B:C/grid.nc"

lig_prmtop = "/home/jim/Desktop/FFT_notebook/1.amber/1AVZ_B:C/ligand.prmtop"
lig_inpcrd = "/home/jim/Desktop/FFT_notebook/2.minimize/1AVZ_B:C/ligand.inpcrd"



def _create_rec_grid(rec_prmtop, lj_sigma_scal_fact, rec_inpcrd, bsite_file, grid_nc_file):
    rec_grid = RecGrid(rec_prmtop, lj_sigma_scal_fact, rec_inpcrd, bsite_file, 
                        grid_nc_file, new_calculation=False)
    return rec_grid

def _create_lig_grid(lig_prmtop, lj_sigma_scal_fact, lig_inpcrd, rec_grid):
    lig_grid = LigGrid(lig_prmtop, lj_sigma_scal_fact, lig_inpcrd, rec_grid)
    return lig_grid

rec_grid = _create_rec_grid(rec_prmtop, lj_sigma_scal_fact, rec_inpcrd, bsite_file, grid_nc_file)

lig_grid = _create_lig_grid(lig_prmtop, lj_sigma_scal_fact, lig_inpcrd, rec_grid)



    

[0.8]
/home/jim/Desktop/FFT_notebook/4.receptor_grid/1AVZ_B:C/grid.nc
[  0.    0.5   1.    1.5   2.    2.5   3.    3.5   4.    4.5   5.    5.5
   6.    6.5   7.    7.5   8.    8.5   9.    9.5  10.   10.5  11.   11.5
  12.   12.5  13.   13.5  14.   14.5  15.   15.5  16.   16.5  17.   17.5
  18.   18.5  19.   19.5  20.   20.5  21.   21.5  22.   22.5  23.   23.5
  24.   24.5  25.   25.5  26.   26.5  27.   27.5  28.   28.5  29.   29.5
  30.   30.5  31.   31.5  32.   32.5  33.   33.5  34.   34.5  35.   35.5
  36.   36.5  37.   37.5  38.   38.5  39.   39.5  40.   40.5  41.   41.5
  42.   42.5  43.   43.5  44.   44.5  45.   45.5  46.   46.5  47.   47.5
  48.   48.5  49.   49.5  50.   50.5  51.   51.5  52.   52.5  53.   53.5
  54.   54.5  55.   55.5  56.   56.5  57.   57.5  58.   58.5  59.   59.5
  60.   60.5  61.   61.5  62.   62.5  63.   63.5  64.   64.5  65.   65.5
  66.   66.5  67.   67.5  68.   68.5  69.   69.5  70.   70.5  71.   71.5
  72.   72.5  73.   73.5  74.   74.5  75.   75.5  76. 

## Print out every translation of a given rotation

In [4]:
# Translate atoms of ligand by every translation vector, sequentially.
# Then write PDB files for each translation. 
import IO
for i, vector in enumerate(resampled_trans_vectors[0][:]):
    print(vector, resampled_energies[0][i])
    
trans_lig_crd = []


# Write a single translation (default the first one) for a specified rotation
# trans_vector = resampled_trans_vectors[0][0]
# shifted_crds = []
# for j, crd in enumerate(lig_positions[0]):
#     shifted_crds.append([crd[0]+(trans_vector[0]*.5), crd[1]+(trans_vector[1]*.5),crd[2]+(trans_vector[2]*.5)])
# shifted_array = np.array(shifted_crds)
# IO.write_pdb(lig_prmtop, shifted_array, '/home/jim/Desktop/FFT_notebook/7.analysis/1AVZ_B:C/rotation0_translation0.pdb', "w")

# Write all of the translations for a given rotation (default is native rotation)
for k, trans_vector in enumerate(resampled_trans_vectors[0][:]):
    shifted_crds = []
    for j, crd in enumerate(lig_positions[0]):
        shifted_crds.append([crd[0]+(trans_vector[0]*.5), crd[1]+(trans_vector[1]*.5),crd[2]+(trans_vector[2]*.5)])
    shifted_array = np.array(shifted_crds)
    IO.write_pdb(lig_prmtop, shifted_array, '/home/jim/Desktop/FFT_notebook/7.analysis/1AVZ_B:C/rotation0_translation%s.pdb'%k, "w")
    

(array([90, 81, 42]), -290.5134743960163)
(array([90, 80, 42]), -285.69731967230797)
(array([88, 81, 41]), -278.4635484202155)
(array([90, 79, 42]), -278.7290405182205)
(array([89, 81, 41]), -270.2009572864218)
(array([89, 82, 41]), -271.82444500283793)
(array([87, 80, 41]), -270.99229506716625)
(array([90, 80, 41]), -268.4018245413908)
(array([89, 80, 41]), -266.50521516452847)
(array([88, 80, 41]), -263.7623633339796)
(array([90, 79, 41]), -262.78809995901895)
(array([135,  29,  14]), -259.6943504474875)
(array([89, 79, 41]), -260.78256301575664)
(array([91, 78, 41]), -258.13407105096627)
(array([88, 79, 41]), -258.2053177986391)
(array([90, 78, 41]), -256.05968109064247)
(array([91, 80, 40]), -255.6284090158363)
(array([136,  30,  14]), -256.41307171323217)
(array([89, 82, 40]), -254.94790373350446)
(array([137,  30,  14]), -254.1958541280682)
(array([89, 78, 41]), -253.65340421221754)
(array([87, 79, 41]), -254.18455762179832)
(array([119,  34,  20]), -253.73858722729972)
(array([9