In [1]:
import netCDF4 as nc
import numpy as np

#fft_path = '/home/jim/Desktop/FFT_notebook/BPMFwFFT/examples/fft_sampling/t4_benzene'
fft_path = '/home/jim/Desktop/FFT_notebook/5.fft_sampling/1AVZ_B:C'
fft_sample_nc = '%s/fft_sample.nc'%fft_path

variable_names = nc.Dataset(fft_sample_nc, 'r').variables
rec_positions = nc.Dataset(fft_sample_nc, 'r').variables["rec_positions"][:]
lig_positions = nc.Dataset(fft_sample_nc, 'r').variables["lig_positions"][:]
lig_com = nc.Dataset(fft_sample_nc, 'r').variables["lig_com"][:]
volume = nc.Dataset(fft_sample_nc, 'r').variables["volume"][:]
nr_grid_points = nc.Dataset(fft_sample_nc, 'r').variables["nr_grid_points"][:]
exponential_sums = nc.Dataset(fft_sample_nc, 'r').variables["exponential_sums"][:]
log_of_divisors = nc.Dataset(fft_sample_nc, 'r').variables["log_of_divisors"][:]

mean_energy = nc.Dataset(fft_sample_nc, 'r').variables["mean_energy"][:]
min_energy = nc.Dataset(fft_sample_nc, 'r').variables["min_energy"][:]
resampled_energies = nc.Dataset(fft_sample_nc, 'r').variables["resampled_energies"][:]
resampled_trans_vectors = nc.Dataset(fft_sample_nc, 'r').variables["resampled_trans_vectors"][:]
print(resampled_trans_vectors[:])
print(resampled_energies[:])

#grid coordinates
origin = nc.Dataset(fft_sample_nc, 'r').variables["origin"][:]
x = nc.Dataset(fft_sample_nc, 'r').variables["x"][:]
y = nc.Dataset(fft_sample_nc, 'r').variables["y"][:]
z = nc.Dataset(fft_sample_nc, 'r').variables["z"][:]
d = nc.Dataset(fft_sample_nc, 'r').variables["d1"][:]
lj_sigma_scaling_factor = nc.Dataset(fft_sample_nc, 'r').variables["lj_sigma_scaling_factor"]

for name in variable_names:
    print(name)

print(lig_positions.shape)
print(resampled_energies.shape)
print(resampled_trans_vectors.shape)
print(np.amin(resampled_energies[0]))
min_index = np.where(resampled_energies[0] == resampled_energies[0].min())
print(min_index)
print(float(resampled_energies[0][min_index]))
print(resampled_trans_vectors[0][min_index])

[[[ 89  81  41]
  [ 90  80  41]
  [ 89  80  41]
  ...
  [115  33  18]
  [116  29  21]
  [ 79  85  42]]]
[[-270.20095729 -268.40182454 -266.50521516 -263.76236333 -262.78809996
  -260.78256302 -258.2053178  -256.41307171 -254.19585413 -256.05968109
  -254.18455762 -253.65340421 -253.54265324 -252.29762463 -253.29791994
  -253.73858723 -252.45786748 -252.79392521 -251.53473518 -250.49548913
  -250.90190606 -252.23886523 -250.97178073 -250.95516821 -249.4923852
  -250.41975413 -250.78181244 -250.96259767 -249.67195558 -248.77068688
  -249.22817805 -248.40998324 -245.85551011 -248.02158512 -247.7071708
  -249.2583227  -248.4625774  -248.56186589 -246.92327812 -247.91298215
  -248.27805106 -248.71200437 -247.87108343 -246.78492498 -247.5684656
  -247.52659549 -246.89125165 -245.92639566 -246.83712377 -246.10889142
  -244.16313786 -245.79444495 -245.86283933 -245.1487838  -245.73508456
  -245.1954588  -244.57187828 -245.19968484 -243.31160965 -246.06465593
  -245.71788701 -245.21650865 -245.

In [2]:
import netCDF4 as nc
import numpy as np

grid_path = '/home/jim/Desktop/FFT_notebook/4.receptor_grid/1AVZ_B:C'
grid_nc = '%s/grid.nc'%grid_path


#parsing some of the netcdf variables from grid.nc
grid_variables = nc.Dataset(grid_nc, 'r').variables
counts = nc.Dataset(grid_nc, 'r').variables["counts"][:]
x = nc.Dataset(grid_nc, 'r').variables["x"][:]
y = nc.Dataset(grid_nc, 'r').variables["y"][:]
z = nc.Dataset(grid_nc, 'r').variables["z"][:]
electrostatic = nc.Dataset(grid_nc, 'r').variables["electrostatic"][:]
lja = nc.Dataset(grid_nc, 'r').variables["LJa"][:]
ljr = nc.Dataset(grid_nc, 'r').variables["LJr"][:]
occupancy = nc.Dataset(grid_nc, 'r').variables["occupancy"][:]
trans_crd = nc.Dataset(grid_nc, 'r').variables["trans_crd"][:]

#DELETE ME: print statements for inspecting the contents of grid.nc
#print(len(occupancy[200][:]))
#print(grid_variables)
kttc = []
for key in grid_variables:
    kttc.append(key)
    print(grid_variables[key])
print(kttc)
print(counts)
#electrostatic grid is accessed by grid[x][y][z], to be confirmed. Alternative is grid[z][y][x]
#below code accesses electrostatic grid values for 3 points on the same axis
print(electrostatic[0][0][0],electrostatic[0][0][1],electrostatic[0][0][2])
#identifies occupied positions on the grid 
occupied_list = [i for i in range(len(occupancy[50][50])) if occupancy[50][50][i] == 1] 
          
# printing resultant list  
print ("New indices list : " + str(occupied_list)) 

#for i in res_list:
#    print(electrostatic[200][200][i])
    
#print(trans_crd)
#print(trans_crd[:])

def multiply_grids(electrostatic_grid, lja_grid, ljr_grid, occupancy_grid):
    grid_dot = np.empty((electrostatic_grid.shape[0], electrostatic_grid.shape[1], electrostatic_grid.shape[2]))
    for i in range(electrostatic_grid.shape[0]):
        for j in range(electrostatic_grid.shape[1]):
            for k in range(electrostatic_grid.shape[2]):
                grid_dot[i][j][k] = np.dot(electrostatic_grid[i][j][k], lja_grid[i][j][k])
                grid_dot[i][j][k] = np.dot(grid_dot[i][j][k], ljr_grid[i][j][k])
    return grid_dot

def get_meaningful_energies(energies):
    for i in range(energies.shape[0]):
        for j in range(energies.shape[1]):
            for k in range(energies.shape[2]):
                if energies[i][j][k] > 0.5:
                    print(energies[i][j][k])


#result = multiply_grids(electrostatic, lja, ljr, occupancy)
#get_meaningful_energies(result)
#print(result)
for i in trans_crd:
    if i[0] > 140:
        print(i)
    
native_trans = [i for i in range(len(trans_crd[:])) if trans_crd[i][0] == 140] 
print(len(trans_crd))
for point in occupied_list:
    print(trans_crd[point])
# get the center of mass of the crystallographic pose, then, get the center of mass for every
# translation of the native rotation and measure the distance between the two points. Select
# the translation with the nearest center of mass as the "native/crystallographic pose"



<type 'netCDF4._netCDF4.Variable'>
float64 lj_sigma_scaling_factor(1)
unlimited dimensions: 
current shape = (1,)
filling on, default _FillValue of 9.96920996839e+36 used

<type 'netCDF4._netCDF4.Variable'>
float64 origin(3)
unlimited dimensions: 
current shape = (3,)
filling on, default _FillValue of 9.96920996839e+36 used

<type 'netCDF4._netCDF4.Variable'>
float64 d0(3)
unlimited dimensions: 
current shape = (3,)
filling on, default _FillValue of 9.96920996839e+36 used

<type 'netCDF4._netCDF4.Variable'>
float64 d1(3)
unlimited dimensions: 
current shape = (3,)
filling on, default _FillValue of 9.96920996839e+36 used

<type 'netCDF4._netCDF4.Variable'>
float64 d2(3)
unlimited dimensions: 
current shape = (3,)
filling on, default _FillValue of 9.96920996839e+36 used

<type 'netCDF4._netCDF4.Variable'>
float64 spacing(3)
unlimited dimensions: 
current shape = (3,)
filling on, default _FillValue of 9.96920996839e+36 used

<type 'netCDF4._netCDF4.Variable'>
int64 counts(3)
unlimited dim

In [3]:
# Create the receptor and ligand grid objects by loading an existing grid calculation result

from grids import RecGrid
from grids import LigGrid

rec_prmtop = "/home/jim/Desktop/FFT_notebook/1.amber/1AVZ_B:C/receptor.prmtop"
lj_sigma_scal_fact = 0.8
rec_inpcrd = "/home/jim/Desktop/FFT_notebook/2.minimize/1AVZ_B:C/receptor.inpcrd"

bsite_file = None
grid_nc_file = "/home/jim/Desktop/FFT_notebook/4.receptor_grid/1AVZ_B:C/grid.nc"

lig_prmtop = "/home/jim/Desktop/FFT_notebook/1.amber/1AVZ_B:C/ligand.prmtop"
lig_inpcrd = "/home/jim/Desktop/FFT_notebook/2.minimize/1AVZ_B:C/ligand.inpcrd"



def _create_rec_grid(rec_prmtop, lj_sigma_scal_fact, rec_inpcrd, bsite_file, grid_nc_file):
    rec_grid = RecGrid(rec_prmtop, lj_sigma_scal_fact, rec_inpcrd, bsite_file, 
                        grid_nc_file, new_calculation=False)
    return rec_grid

def _create_lig_grid(lig_prmtop, lj_sigma_scal_fact, lig_inpcrd, rec_grid):
    lig_grid = LigGrid(lig_prmtop, lj_sigma_scal_fact, lig_inpcrd, rec_grid)
    return lig_grid

rec_grid = _create_rec_grid(rec_prmtop, lj_sigma_scal_fact, rec_inpcrd, bsite_file, grid_nc_file)

lig_grid = _create_lig_grid(lig_prmtop, lj_sigma_scal_fact, lig_inpcrd, rec_grid)



    

[0.8]
/home/jim/Desktop/FFT_notebook/4.receptor_grid/1AVZ_B:C/grid.nc
[  0.    0.5   1.    1.5   2.    2.5   3.    3.5   4.    4.5   5.    5.5
   6.    6.5   7.    7.5   8.    8.5   9.    9.5  10.   10.5  11.   11.5
  12.   12.5  13.   13.5  14.   14.5  15.   15.5  16.   16.5  17.   17.5
  18.   18.5  19.   19.5  20.   20.5  21.   21.5  22.   22.5  23.   23.5
  24.   24.5  25.   25.5  26.   26.5  27.   27.5  28.   28.5  29.   29.5
  30.   30.5  31.   31.5  32.   32.5  33.   33.5  34.   34.5  35.   35.5
  36.   36.5  37.   37.5  38.   38.5  39.   39.5  40.   40.5  41.   41.5
  42.   42.5  43.   43.5  44.   44.5  45.   45.5  46.   46.5  47.   47.5
  48.   48.5  49.   49.5  50.   50.5  51.   51.5  52.   52.5  53.   53.5
  54.   54.5  55.   55.5  56.   56.5  57.   57.5  58.   58.5  59.   59.5
  60.   60.5  61.   61.5  62.   62.5  63.   63.5  64.   64.5  65.   65.5
  66.   66.5  67.   67.5  68.   68.5  69.   69.5  70.   70.5  71.   71.5
  72.   72.5  73.   73.5  74.   74.5  75.   75.5  76. 

## Calculate the per atom SASA for R&L

In [4]:
# Translate atoms of ligand by every translation vector, sequentially.
# Then write PDB files for each translation. 
import IO
import mdtraj

mdtraj_receptor = mdtraj.load('/home/jim/Desktop/FFT_notebook/2.minimize/1AVZ_B:C/receptor.inpcrd', top='/home/jim/Desktop/FFT_notebook/1.amber/1AVZ_B:C/receptor.prmtop')
mdtraj_ligand = mdtraj.load('/home/jim/Desktop/FFT_notebook/1.amber/1AVZ_B:C/ligand.inpcrd', top='/home/jim/Desktop/FFT_notebook/1.amber/1AVZ_B:C/ligand.prmtop')

receptor_sasa = mdtraj.shrake_rupley(mdtraj_receptor, mode='atom')
# ligand_sasa

receptor_core_atoms = []
receptor_surface_atoms = []
for atom in receptor_sasa[0]:
    if atom > 0.1:
        receptor_surface_atoms.append(atom)
    else:
        receptor_core_atoms.append(atom)

print(len(receptor_core_atoms))
print(len(receptor_surface_atoms))
    

1564
275


In [15]:
ATOMIC_RADII = {'H'   : 0.120, 'He'  : 0.140, 'Li'  : 0.076, 'Be' : 0.059, 
                 'B'   : 0.192, 'C'   : 0.170, 'N'   : 0.155, 'O'  : 0.152, 
                 'F'   : 0.147, 'Ne'  : 0.154, 'Na'  : 0.102, 'Mg' : 0.086, 
                 'Al'  : 0.184, 'Si'  : 0.210, 'P'   : 0.180, 'S'  : 0.180, 
                 'Cl'  : 0.181, 'Ar'  : 0.188, 'K'   : 0.138, 'Ca' : 0.114, 
                 'Sc'  : 0.211, 'Ti'  : 0.200, 'V'   : 0.200, 'Cr' : 0.200, 
                 'Mn'  : 0.200, 'Fe'  : 0.200, 'Co'  : 0.200, 'Ni' : 0.163, 
                 'Cu'  : 0.140, 'Zn'  : 0.139, 'Ga'  : 0.187, 'Ge' : 0.211, 
                 'As'  : 0.185, 'Se'  : 0.190, 'Br'  : 0.185, 'Kr' : 0.202, 
                 'Rb'  : 0.303, 'Sr'  : 0.249, 'Y'   : 0.200, 'Zr' : 0.200, 
                 'Nb'  : 0.200, 'Mo'  : 0.200, 'Tc'  : 0.200, 'Ru' : 0.200, 
                 'Rh'  : 0.200, 'Pd'  : 0.163, 'Ag'  : 0.172, 'Cd' : 0.158, 
                 'In'  : 0.193, 'Sn'  : 0.217, 'Sb'  : 0.206, 'Te' : 0.206, 
                 'I'   : 0.198, 'Xe'  : 0.216, 'Cs'  : 0.167, 'Ba' : 0.149, 
                 'La'  : 0.200, 'Ce'  : 0.200, 'Pr'  : 0.200, 'Nd' : 0.200, 
                 'Pm'  : 0.200, 'Sm'  : 0.200, 'Eu'  : 0.200, 'Gd' : 0.200, 
                 'Tb'  : 0.200, 'Dy'  : 0.200, 'Ho'  : 0.200, 'Er' : 0.200, 
                 'Tm'  : 0.200, 'Yb'  : 0.200, 'Lu'  : 0.200, 'Hf' : 0.200, 
                 'Ta'  : 0.200, 'W'   : 0.200, 'Re'  : 0.200, 'Os' : 0.200, 
                 'Ir'  : 0.200, 'Pt'  : 0.175, 'Au'  : 0.166, 'Hg' : 0.155, 
                 'Tl'  : 0.196, 'Pb'  : 0.202, 'Bi'  : 0.207, 'Po' : 0.197, 
                 'At'  : 0.202, 'Rn'  : 0.220, 'Fr'  : 0.348, 'Ra' : 0.283, 
                 'Ac'  : 0.200, 'Th'  : 0.200, 'Pa'  : 0.200, 'U'  : 0.186, 
                 'Np'  : 0.200, 'Pu'  : 0.200, 'Am'  : 0.200, 'Cm' : 0.200, 
                 'Bk'  : 0.200, 'Cf'  : 0.200, 'Es'  : 0.200, 'Fm' : 0.200, 
                 'Md'  : 0.200, 'No'  : 0.200, 'Lr'  : 0.200, 'Rf' : 0.200, 
                 'Db'  : 0.200, 'Sg'  : 0.200, 'Bh'  : 0.200, 'Hs' : 0.200, 
                 'Mt'  : 0.200, 'Ds'  : 0.200, 'Rg'  : 0.200, 'Cn' : 0.200, 
                 'Uut' : 0.200, 'Fl'  : 0.200, 'Uup' : 0.200, 'Lv' : 0.200, 
                 'Uus' : 0.200, 'Uuo' : 0.200} 

allH = mdtraj_receptor.topology.atoms_by_name('H')

print(mdtraj_receptor.topology.atom(10))

protein_atomic_radii = []

for atom_label in mdtraj_receptor.top.atoms:
    protein_atomic_radii.append(ATOMIC_RADII[str(atom_label).split("-",1)[1][0]])

# print(protein_atomic_radii)

VAL0-HG12


In [17]:
# for atom in mdtraj_receptor.xyz[0]: 

receptor_sasa_grid = np.zeros((x.size,y.size,z.size))

for index, atom in enumerate(rec_positions): 
    point1 = atom
    min_dist = 1000
    for i in x:
        for j in y:
            for k in z:
                point2 = [i,j,k]
                dist = np.linalg.norm(point1 - point2)
                if receptor_sasa[0][index] > 0.1 and dist < (np.sqrt(0.8)*protein_atomic_radii[index]):
                    receptor_sasa_grid[i,j,k] = 1
                elif dist < (np.sqrt(1.5)*protein_atomic_radii[index]):
                    
                    
                    
#         print(min_dist)
            # dist = np.linalg.norm(point1 - point2)
print(receptor_sasa_grid)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [11]:
print(rec_positions.shape)
print(receptor_sasa.shape)
print(x.size)
print(receptor_sasa)

(1839, 3)
(1, 1839)
247
[[0.0125307  0.11680441 0.22741464 ... 0.02641687 0.15179002 0.09152046]]
