In [1]:
from os import walk
import os


f = []
for root, dirs, files in walk("/media/jim/Research_TWO/FFT_PPI/2.redock/4.receptor_grid", topdown=False):
   # for name in files:
   #    print(os.path.join(root, name))
    for name in dirs:
        # print(os.path.join(name))
        f.append(name)

In [2]:
from math import sqrt
grid_type = 'empty'
f.sort()
for dirname in f:
    # print(f"""python /home/jim/src/p39/bpmfwfft/protein_protein_scripts/run_receptor_grid_cal.py --amber_dir /media/jim/Research_TWO/FFT_PPI/2.redock/1.amber/{dirname} --coord_dir /media/jim/Research_TWO/FFT_PPI/2.redock/2.minimize/{dirname} --out_dir /media/jim/Research_TWO/FFT_PPI/2.redock/4.receptor_grid/{dirname} --lj_scale 1.000000 ----spacing 0.500000 --buffer 1.000000""")
    # print(f"""python /home/jim/src/p39/bpmfwfft/protein_protein_scripts/run_receptor_grid_cal.py\
    # --amber_dir /media/jim/Research_TWO/FFT_PPI/2.redock/1.amber/{dirname}\
    # --coord_dir /media/jim/Research_TWO/FFT_PPI/2.redock/2.minimize/{dirname}\
    # --out_dir /media/jim/Research_TWO/FFT_PPI/2.redock/4.receptor_grid/{dirname}\
    # --lj_scale 1.000000 --sc_score {sqrt(1.5)} --ss_score {sqrt(0.8)}\
    # --spacing 0.500000 --buffer 1.000000""")
    if grid_type == 'sasa':
        print(f"""python /home/jim/src/p39/bpmfwfft/protein_protein_scripts/run_receptor_grid_cal.py\
        --amber_dir /media/jim/Research_TWO/FFT_PPI/2.redock/1.amber/{dirname}\
        --coord_dir /media/jim/Research_TWO/FFT_PPI/2.redock/2.minimize/{dirname}\
        --out_dir /media/jim/Research_TWO/FFT_PPI/2.redock/4.receptor_grid/{dirname}\
        --grid_file_name sasa_grid_noH.nc\
        --lj_scale 1.000000\
        --spacing 0.500000 --buffer 1.000000\
        --exclude_H True
        """)
        print('')
    elif grid_type == 'empty':
        print(f"""python /home/jim/src/p39/bpmfwfft/protein_protein_scripts/run_receptor_grid_cal.py\
        --amber_dir /media/jim/Research_TWO/FFT_PPI/2.redock/1.amber/{dirname}\
        --coord_dir /media/jim/Research_TWO/FFT_PPI/2.redock/2.minimize/{dirname}\
        --out_dir /media/jim/Research_TWO/FFT_PPI/2.redock/4.receptor_grid/{dirname}\
        --grid_file_name empty_grid.nc\
        --lj_scale 1.000000\
        --spacing 0.500000 --buffer 1.000000\
        --exclude_H True
        """)

python /home/jim/src/p39/bpmfwfft/protein_protein_scripts/run_receptor_grid_cal.py        --amber_dir /media/jim/Research_TWO/FFT_PPI/2.redock/1.amber/.ipynb_checkpoints        --coord_dir /media/jim/Research_TWO/FFT_PPI/2.redock/2.minimize/.ipynb_checkpoints        --out_dir /media/jim/Research_TWO/FFT_PPI/2.redock/4.receptor_grid/.ipynb_checkpoints        --grid_file_name empty_grid.nc        --lj_scale 1.000000        --spacing 0.500000 --buffer 1.000000        --exclude_H True
        
python /home/jim/src/p39/bpmfwfft/protein_protein_scripts/run_receptor_grid_cal.py        --amber_dir /media/jim/Research_TWO/FFT_PPI/2.redock/1.amber/1A2K_C:AB        --coord_dir /media/jim/Research_TWO/FFT_PPI/2.redock/2.minimize/1A2K_C:AB        --out_dir /media/jim/Research_TWO/FFT_PPI/2.redock/4.receptor_grid/1A2K_C:AB        --grid_file_name empty_grid.nc        --lj_scale 1.000000        --spacing 0.500000 --buffer 1.000000        --exclude_H True
        
python /home/jim/src/p39/bpmfwfft/pro

In [26]:
system_name = "2OOB_A:B"
for n,i in enumerate([1.0, sqrt(1.1), sqrt(1.2), sqrt(1.3), sqrt(1.4), sqrt(1.5)]):
    fn = n+1
    print(f"""python /home/jim/src/p39/bpmfwfft/protein_protein_scripts/run_receptor_grid_cal.py\
        --amber_dir /media/jim/Research_TWO/FFT_PPI/2.redock/1.amber/{system_name}\
        --coord_dir /media/jim/Research_TWO/FFT_PPI/2.redock/2.minimize/{system_name}\
        --out_dir /media/jim/Research_TWO/FFT_PPI/2.redock/4.receptor_grid/{system_name}\
        --grid_file_name grid_sc_sqrt1_{n}.nc\
        --lj_scale 1.000000\
        --sc_scale {i}\
        --spacing 0.500000 --buffer 1.000000""")
    print('')

python /home/jim/src/p39/bpmfwfft/protein_protein_scripts/run_receptor_grid_cal.py        --amber_dir /media/jim/Research_TWO/FFT_PPI/2.redock/1.amber/2OOB_A:B        --coord_dir /media/jim/Research_TWO/FFT_PPI/2.redock/2.minimize/2OOB_A:B        --out_dir /media/jim/Research_TWO/FFT_PPI/2.redock/4.receptor_grid/2OOB_A:B        --grid_file_name grid_sc_sqrt1_0.nc        --lj_scale 1.000000        --sc_scale 1.0        --spacing 0.500000 --buffer 1.000000

python /home/jim/src/p39/bpmfwfft/protein_protein_scripts/run_receptor_grid_cal.py        --amber_dir /media/jim/Research_TWO/FFT_PPI/2.redock/1.amber/2OOB_A:B        --coord_dir /media/jim/Research_TWO/FFT_PPI/2.redock/2.minimize/2OOB_A:B        --out_dir /media/jim/Research_TWO/FFT_PPI/2.redock/4.receptor_grid/2OOB_A:B        --grid_file_name grid_sc_sqrt1_1.nc        --lj_scale 1.000000        --sc_scale 1.0488088481701516        --spacing 0.500000 --buffer 1.000000

python /home/jim/src/p39/bpmfwfft/protein_protein_scripts/run_rec

In [8]:
# Pairwise multplication test
# Create test cases where scores are known
# Tests required:
# Score of 1
#     -A single overlap between the real part of the SASA grids
#     -This may be a problem depending on the shape of the protein
#     -Create a function to count the number of grid points involved in overlap
#         this will be the same as the score
# Series of scores:
#     -Increasing scores along a single axis until negative
#     -Translate along axis from side to side, build 1D slice of score function
# Score of 0:
#     -No overlap sanity check


In [9]:
##Get list of complex names
from os import walk
import os

f = []
for root, dirs, files in walk("/home/jim/src/p27/FFT_PPI/2.redock/4.receptor_grid", topdown=False):
    for name in dirs:
        f.append(name)
f.sort()

In [10]:
##Set target system TODO: This is for testing, should be automated
system = f[127] # 127 is 200B_A:B
print(system)

2OOB_A:B


In [11]:
##Load receptor grid from disk
import netCDF4 as nc
import numpy as np

grid_path = f'/home/jim/src/p27/FFT_PPI/2.redock/4.receptor_grid/{system}'
grid_nc = f'{grid_path}/grid.nc'


#parsing some of the netcdf variables from grid.nc
grid_variables = nc.Dataset(grid_nc, 'r').variables
counts = nc.Dataset(grid_nc, 'r').variables["counts"][:]
x = nc.Dataset(grid_nc, 'r').variables["x"][:]
y = nc.Dataset(grid_nc, 'r').variables["y"][:]
z = nc.Dataset(grid_nc, 'r').variables["z"][:]
electrostatic = nc.Dataset(grid_nc, 'r').variables["electrostatic"][:]
lja = nc.Dataset(grid_nc, 'r').variables["LJa"][:]
ljr = nc.Dataset(grid_nc, 'r').variables["LJr"][:]
SASAi = nc.Dataset(grid_nc, 'r').variables["SASAi"][:]
SASAr = nc.Dataset(grid_nc, 'r').variables["SASAr"][:]
trans_crd = nc.Dataset(grid_nc, 'r').variables["trans_crd"][:]
rec_displacement = nc.Dataset(grid_nc, 'r').variables["displacement"][:]


In [12]:
# Create the receptor and ligand grid objects by loading an existing grid calculation result

from bpmfwfft.grids import RecGrid
from bpmfwfft.grids import LigGrid

rec_prmtop = f'/home/jim/src/p27/FFT_PPI/2.redock/1.amber/{system}/receptor.prmtop'
lj_sigma_scal_fact = 0.8
rec_inpcrd = f'/home/jim/src/p27/FFT_PPI/2.redock/2.minimize/{system}/receptor.inpcrd'

bsite_file = None
grid_nc_file = f'/home/jim/src/p27/FFT_PPI/2.redock/4.receptor_grid/{system}/grid.nc'

lig_prmtop = f'/home/jim/src/p27/FFT_PPI/2.redock/1.amber/{system}/ligand.prmtop'
lig_inpcrd = f'/home/jim/src/p27/FFT_PPI/2.redock/2.minimize/{system}/ligand.inpcrd'



def _create_rec_grid(rec_prmtop, lj_sigma_scal_fact, rec_inpcrd, bsite_file, grid_nc_file):
    rec_grid = RecGrid(rec_prmtop, lj_sigma_scal_fact, rec_inpcrd, bsite_file, 
                        grid_nc_file, new_calculation=False)
    return rec_grid

def _create_lig_grid(lig_prmtop, lj_sigma_scal_fact, lig_inpcrd, rec_grid):
    lig_grid = LigGrid(lig_prmtop, lj_sigma_scal_fact, lig_inpcrd, rec_grid)
    return lig_grid

rec_grid = _create_rec_grid(rec_prmtop, lj_sigma_scal_fact, rec_inpcrd, bsite_file, grid_nc_file)

lig_grid = _create_lig_grid(lig_prmtop, lj_sigma_scal_fact, lig_inpcrd, rec_grid)

/home/jim/src/p39/jupyter/fftanalysis
[0.8]
/home/jim/src/p27/FFT_PPI/2.redock/4.receptor_grid/2OOB_A:B/grid.nc
[  0.    0.5   1.    1.5   2.    2.5   3.    3.5   4.    4.5   5.    5.5
   6.    6.5   7.    7.5   8.    8.5   9.    9.5  10.   10.5  11.   11.5
  12.   12.5  13.   13.5  14.   14.5  15.   15.5  16.   16.5  17.   17.5
  18.   18.5  19.   19.5  20.   20.5  21.   21.5  22.   22.5  23.   23.5
  24.   24.5  25.   25.5  26.   26.5  27.   27.5  28.   28.5  29.   29.5
  30.   30.5  31.   31.5  32.   32.5  33.   33.5  34.   34.5  35.   35.5
  36.   36.5  37.   37.5  38.   38.5  39.   39.5  40.   40.5  41.   41.5
  42.   42.5  43.   43.5  44.   44.5  45.   45.5  46.   46.5  47.   47.5
  48.   48.5  49.   49.5  50.   50.5  51.   51.5  52.   52.5  53.   53.5
  54.   54.5  55.   55.5  56.   56.5  57.   57.5  58.   58.5  59.   59.5
  60.   60.5  61.   61.5  62.   62.5  63.   63.5  64.   64.5  65.   65.5
  66.   66.5  67.   67.5  68.   68.5  69.   69.5  70.   70.5  71.   71.5
  72.   72.5

In [6]:
# Translate Ligand to crystal pose before calculation
diff_vector = rec_displacement-lig_grid._displacement
displacement = np.array(diff_vector)
lig_grid.translate_ligand(displacement)

In [13]:
#Calculate Ligand SASAi and SASAr grids

grid_x = np.linspace(
        lig_grid._origin_crd[0],
        lig_grid._origin_crd[0] + ((lig_grid._grid["counts"][0]-1) * lig_grid._grid["spacing"][0]),
        num=lig_grid._grid["counts"][0]
    )
grid_y = np.linspace(
    lig_grid._origin_crd[1],
    lig_grid._origin_crd[1] + ((lig_grid._grid["counts"][1] - 1) * lig_grid._grid["spacing"][1]),
    num=lig_grid._grid["counts"][1]
)
grid_z = np.linspace(
    lig_grid._origin_crd[2],
    lig_grid._origin_crd[2] + ((lig_grid._grid["counts"][2] - 1) * lig_grid._grid["spacing"][2]),
    num=lig_grid._grid["counts"][2]
)

uper_most_corner_crd = lig_grid._origin_crd + (lig_grid._grid["counts"] - 1.) * lig_grid._grid["spacing"]
uper_most_corner = (lig_grid._grid["counts"] - 1)

lig_SASAi_grid, lig_SASAr_grid = lig_grid.get_SASA_grids("SASAi", lig_grid._crd,
                                         grid_x, grid_y, grid_z, 
                                         lig_grid._origin_crd, uper_most_corner_crd, uper_most_corner, 
                       lig_grid._grid["spacing"], lig_grid._eight_corner_shifts, lig_grid._six_corner_shifts,
                       lig_grid._nearest_neighbor_shifts, lig_grid._grid["counts"], lig_grid._get_charges("SASAi"),
                       lig_grid._prmtop["LJ_SIGMA"], lig_grid._molecule_sasa)

[ 6 40 19]
9179


In [14]:
### Construct complex SASA grids
rec_sasa_grid = np.add(SASAr, SASAi*1.j)
lig_sasa_grid = np.add(lig_SASAr_grid, lig_SASAi_grid*1.j)


In [17]:
# Find the last index in Ligand with value of 1+0.j
# Find the first index in Receptor with value of 1+0.j
target = 1. + 0.j
lig_last_index = np.array(np.where(lig_sasa_grid == target)).transpose()[-1]
rec_first_index = np.array(np.where(rec_sasa_grid == target)).transpose()[0]


In [23]:
print(rec_first_index-lig_last_index)

[-13 117  36]


In [19]:
print(rec_first_index)

[ 62 127  77]


In [13]:
import numpy as np
grid1 = np.array([[[1,1,1],[1,1,1],[1,1,1]],[[1,1,1],[0,0,0],[1,1,1]],[[1,1,1],[1,1,1],[1,1,1]]])
grid2 = np.array([[[0,0,0],[0,0,0],[0,0,0]],[[0,0,0],[9,9,9],[0,0,0]],[[0,0,0],[0,0,0],[0,0,0]]])
complex_grid = np.add(grid1, grid2*1.j)
pairwise = np.multiply(complex_grid, complex_grid)

In [21]:
print("Pairwise multiplication score:", pairwise.sum())

Pairwise multiplication score: (-219+0j)


In [20]:
fft = np.fft.fftn(grid1*grid2.conjugate())
corr_func = np.fft.ifftn(fft)
print("complex FFT convolution theorem score:", corr_func[0][0][0])

FFT convolution theorem score: 0j


In [22]:
fft_real = np.fft.fftn(grid1)
fft_imag = np.fft.fftn(grid2*1.j)
fft_rr = fft_real*fft_real.conjugate() 
fft_ri = fft_real*fft_imag.conjugate()
fft_ir = fft_imag*fft_real.conjugate()
fft_ii = fft_imag*fft_imag.conjugate()

# (fft_real + fft_imag)(fft_real - fft_imag) = fft_rr - fft_ri + fft_ir - fft_ii

corr_func_parts = np.fft.ifftn(fft_rr - fft_ri + fft_ir - fft_ii)
print("Alternate FFT convolution theorem score:", corr_func_parts[0][0][0])

Alternate FFT convolution theorem score: (-218.99999999999991+9.473903143468002e-15j)
